@url = http://localhost:5000

###
GET  {{url}}

###
GET {{url}}/reservations

###
POST {{url}}/reservations
Content-Type: application/json

{
    "employeename": "Jon Doe",
    "parkingSpotName": "P0",
    "licensePlate": "XYZ123"
}

###
PUT {{url}}/reservations