@url = http://localhost:5000

###
GET  {{url}}

###
GET {{url}}/reservations

###
POST {{url}}/reservations
Content-Type: application/json

{
    "employeename": "Jon Doe",
    "parkingSpotName": "P1",
    "licensePlate": "XYZ123",
    "date": "2023-02-24"
}

###
PUT {{url}}/reservations